services:
  web:
    image: monsters-and-treasure:latest
    container_name: monsters-and-treasure
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 web_game:app

networks:
  game-network:
    driver: bridge 