version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./static
        target: /app/static
        read_only: true
      - type: bind
        source: ./views
        target: /app/views
        read_only: true
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - WORKERS=2
      - TIMEOUT=120
      - KEEP_ALIVE=30
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - game-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        mode: "non-blocking"
        tag: "{{.Name}}"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    command: >
      sh -c "gunicorn
      --bind 0.0.0.0:8000
      --workers 2
      --timeout 120
      --access-logfile /app/logs/gunicorn-access.log
      --error-logfile /app/logs/gunicorn-error.log
      --capture-output
      --log-level debug
      --no-pidfile
      web_game:app"

volumes:
  game_data:
  game_logs:

networks:
  game-network:
    driver: bridge 