services:
  web:
    build: .
    ports:
      - "80:8000"  # Main application port
      - "3025:3025"  # Debug port for browser tools
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static:ro
      - ./views:/app/views:ro
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - PYTHONOPTIMIZE=2
      - DEBUG_PORT=3025
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - game-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        mode: "non-blocking"
        tag: "{{.Name}}"
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    command: gunicorn --config gunicorn.conf.py web_game:app

volumes:
  game_data:
  game_logs:

networks:
  game-network:
    driver: bridge 