version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static:ro
      - ./views:/app/views:ro
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - WORKERS=2
      - TIMEOUT=120
      - KEEP_ALIVE=30
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - game-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

volumes:
  game_data:
  game_logs:

networks:
  game-network:
    driver: bridge 