services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - game-data:/app/data
      - app-logs:/app/logs
    environment:
      - DEVELOPMENT=0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  game-data:
    driver: local
  app-logs:
    driver: local 